#############################################################################
# Makefile for building: QTetris
# Generated by qmake (2.01a) (Qt 4.7.4) on: Thu Mar 29 16:10:39 2012
# Project:  QTetris.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile QTetris.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = TetrisGrid.cpp \
		TetrisScene.cpp \
		QTetrisWindow.cpp \
		Block.cpp \
		BlockFactory.cpp \
		LineBlock.cpp \
		LBlock.cpp \
		JBlock.cpp \
		TBlock.cpp \
		GameBorder.cpp \
		main.cpp moc_TetrisGrid.cpp \
		moc_QTetrisWindow.cpp \
		moc_BlockFactory.cpp
OBJECTS       = TetrisGrid.o \
		TetrisScene.o \
		QTetrisWindow.o \
		Block.o \
		BlockFactory.o \
		LineBlock.o \
		LBlock.o \
		JBlock.o \
		TBlock.o \
		GameBorder.o \
		main.o \
		moc_TetrisGrid.o \
		moc_QTetrisWindow.o \
		moc_BlockFactory.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		QTetris.pro
QMAKE_TARGET  = QTetris
DESTDIR       = 
TARGET        = QTetris

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QTetris.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile QTetris.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile QTetris.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/QTetris1.0.0 || $(MKDIR) .tmp/QTetris1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/QTetris1.0.0/ && $(COPY_FILE) --parents TetrisGrid.h TetrisScene.h QTetrisWindow.h Block.h BlockFactory.h LineBlock.h LBlock.h JBlock.h TBlock.h GameBorder.h .tmp/QTetris1.0.0/ && $(COPY_FILE) --parents TetrisGrid.cpp TetrisScene.cpp QTetrisWindow.cpp Block.cpp BlockFactory.cpp LineBlock.cpp LBlock.cpp JBlock.cpp TBlock.cpp GameBorder.cpp main.cpp .tmp/QTetris1.0.0/ && (cd `dirname .tmp/QTetris1.0.0` && $(TAR) QTetris1.0.0.tar QTetris1.0.0 && $(COMPRESS) QTetris1.0.0.tar) && $(MOVE) `dirname .tmp/QTetris1.0.0`/QTetris1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/QTetris1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_TetrisGrid.cpp moc_QTetrisWindow.cpp moc_BlockFactory.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_TetrisGrid.cpp moc_QTetrisWindow.cpp moc_BlockFactory.cpp
moc_TetrisGrid.cpp: Block.h \
		GameBorder.h \
		BlockFactory.h \
		TetrisGrid.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) TetrisGrid.h -o moc_TetrisGrid.cpp

moc_QTetrisWindow.cpp: TetrisScene.h \
		TetrisGrid.h \
		Block.h \
		GameBorder.h \
		BlockFactory.h \
		QTetrisWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) QTetrisWindow.h -o moc_QTetrisWindow.cpp

moc_BlockFactory.cpp: Block.h \
		BlockFactory.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) BlockFactory.h -o moc_BlockFactory.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

TetrisGrid.o: TetrisGrid.cpp TetrisGrid.h \
		Block.h \
		GameBorder.h \
		BlockFactory.h \
		LineBlock.h \
		LBlock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TetrisGrid.o TetrisGrid.cpp

TetrisScene.o: TetrisScene.cpp TetrisScene.h \
		TetrisGrid.h \
		Block.h \
		GameBorder.h \
		BlockFactory.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TetrisScene.o TetrisScene.cpp

QTetrisWindow.o: QTetrisWindow.cpp QTetrisWindow.h \
		TetrisScene.h \
		TetrisGrid.h \
		Block.h \
		GameBorder.h \
		BlockFactory.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QTetrisWindow.o QTetrisWindow.cpp

Block.o: Block.cpp Block.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Block.o Block.cpp

BlockFactory.o: BlockFactory.cpp BlockFactory.h \
		Block.h \
		LineBlock.h \
		LBlock.h \
		JBlock.h \
		TBlock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BlockFactory.o BlockFactory.cpp

LineBlock.o: LineBlock.cpp LineBlock.h \
		Block.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LineBlock.o LineBlock.cpp

LBlock.o: LBlock.cpp LBlock.h \
		Block.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LBlock.o LBlock.cpp

JBlock.o: JBlock.cpp JBlock.h \
		Block.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o JBlock.o JBlock.cpp

TBlock.o: TBlock.cpp TBlock.h \
		Block.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TBlock.o TBlock.cpp

GameBorder.o: GameBorder.cpp GameBorder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GameBorder.o GameBorder.cpp

main.o: main.cpp QTetrisWindow.h \
		TetrisScene.h \
		TetrisGrid.h \
		Block.h \
		GameBorder.h \
		BlockFactory.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

moc_TetrisGrid.o: moc_TetrisGrid.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TetrisGrid.o moc_TetrisGrid.cpp

moc_QTetrisWindow.o: moc_QTetrisWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QTetrisWindow.o moc_QTetrisWindow.cpp

moc_BlockFactory.o: moc_BlockFactory.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_BlockFactory.o moc_BlockFactory.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

