#############################################################################
# Makefile for building: QTetris.app/Contents/MacOS/QTetris
# Generated by qmake (2.01a) (Qt 4.8.0) on: Sat Mar 24 21:09:31 2012
# Project:  QTetris.pro
# Template: app
# Command: /Users/andrew/QtSDK/Desktop/Qt/4.8.0/gcc/bin/qmake -o Makefile QTetris.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/default -I. -I../../../QtSDK/Desktop/Qt/4.8.0/gcc/lib/QtCore.framework/Versions/4/Headers -I../../../QtSDK/Desktop/Qt/4.8.0/gcc/include/QtCore -I../../../QtSDK/Desktop/Qt/4.8.0/gcc/lib/QtGui.framework/Versions/4/Headers -I../../../QtSDK/Desktop/Qt/4.8.0/gcc/include/QtGui -I../../../QtSDK/Desktop/Qt/4.8.0/gcc/include -I. -I. -F/Users/andrew/QtSDK/Desktop/Qt/4.8.0/gcc/lib
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/Users/andrew/QtSDK/Desktop/Qt/4.8.0/gcc/lib -L/Users/andrew/QtSDK/Desktop/Qt/4.8.0/gcc/lib -framework QtGui -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Users/andrew/QtSDK/Desktop/Qt/4.8.0/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = TetrisGrid.cpp \
		TetrisScene.cpp \
		QTetrisWindow.cpp \
		Block.cpp \
		BlockFactory.cpp \
		LineBlock.cpp \
		LBlock.cpp \
		JBlock.cpp \
		TBlock.cpp \
		GameBorder.cpp \
		main.cpp moc_TetrisGrid.cpp \
		moc_QTetrisWindow.cpp \
		moc_BlockFactory.cpp
OBJECTS       = TetrisGrid.o \
		TetrisScene.o \
		QTetrisWindow.o \
		Block.o \
		BlockFactory.o \
		LineBlock.o \
		LBlock.o \
		JBlock.o \
		TBlock.o \
		GameBorder.o \
		main.o \
		moc_TetrisGrid.o \
		moc_QTetrisWindow.o \
		moc_BlockFactory.o
DIST          = ../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/mac.conf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-macx.conf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-macx.conf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_pre.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/dwarf2.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/debug.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_post.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/x86_64.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/objective_c.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/rez.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/sdk.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf \
		QTetris.pro
QMAKE_TARGET  = QTetris
DESTDIR       = 
TARGET        = QTetris.app/Contents/MacOS/QTetris

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile QTetris.app/Contents/PkgInfo QTetris.app/Contents/Resources/empty.lproj QTetris.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) QTetris.app/Contents/MacOS/ || $(MKDIR) QTetris.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QTetris.pro  ../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/default/qmake.conf ../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/mac.conf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-macx.conf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-macx.conf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_pre.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/dwarf2.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/debug.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_post.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/x86_64.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/objective_c.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/rez.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/sdk.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile QTetris.pro
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/mac.conf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-macx.conf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-macx.conf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_pre.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/dwarf2.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/debug.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_post.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/x86_64.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/objective_c.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/rez.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/sdk.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -o Makefile QTetris.pro

QTetris.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) QTetris.app/Contents || $(MKDIR) QTetris.app/Contents 
	@$(DEL_FILE) QTetris.app/Contents/PkgInfo
	@echo "APPL????" >QTetris.app/Contents/PkgInfo
QTetris.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) QTetris.app/Contents/Resources || $(MKDIR) QTetris.app/Contents/Resources 
	@touch QTetris.app/Contents/Resources/empty.lproj
	
QTetris.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) QTetris.app/Contents || $(MKDIR) QTetris.app/Contents 
	@$(DEL_FILE) QTetris.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,QTetris,g" -e "s,@TYPEINFO@,????,g" ../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/default/Info.plist.app >QTetris.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/QTetris1.0.0 || $(MKDIR) .tmp/QTetris1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/QTetris1.0.0/ && $(COPY_FILE) --parents TetrisGrid.h TetrisScene.h QTetrisWindow.h Block.h BlockFactory.h LineBlock.h LBlock.h JBlock.h TBlock.h GameBorder.h .tmp/QTetris1.0.0/ && $(COPY_FILE) --parents TetrisGrid.cpp TetrisScene.cpp QTetrisWindow.cpp Block.cpp BlockFactory.cpp LineBlock.cpp LBlock.cpp JBlock.cpp TBlock.cpp GameBorder.cpp main.cpp .tmp/QTetris1.0.0/ && (cd `dirname .tmp/QTetris1.0.0` && $(TAR) QTetris1.0.0.tar QTetris1.0.0 && $(COMPRESS) QTetris1.0.0.tar) && $(MOVE) `dirname .tmp/QTetris1.0.0`/QTetris1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/QTetris1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r QTetris.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_TetrisGrid.cpp moc_QTetrisWindow.cpp moc_BlockFactory.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_TetrisGrid.cpp moc_QTetrisWindow.cpp moc_BlockFactory.cpp
moc_TetrisGrid.cpp: Block.h \
		GameBorder.h \
		BlockFactory.h \
		TetrisGrid.h
	/Users/andrew/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ TetrisGrid.h -o moc_TetrisGrid.cpp

moc_QTetrisWindow.cpp: TetrisScene.h \
		TetrisGrid.h \
		Block.h \
		GameBorder.h \
		BlockFactory.h \
		QTetrisWindow.h
	/Users/andrew/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ QTetrisWindow.h -o moc_QTetrisWindow.cpp

moc_BlockFactory.cpp: Block.h \
		BlockFactory.h
	/Users/andrew/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ BlockFactory.h -o moc_BlockFactory.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

TetrisGrid.o: TetrisGrid.cpp TetrisGrid.h \
		Block.h \
		GameBorder.h \
		BlockFactory.h \
		LineBlock.h \
		LBlock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TetrisGrid.o TetrisGrid.cpp

TetrisScene.o: TetrisScene.cpp TetrisScene.h \
		TetrisGrid.h \
		Block.h \
		GameBorder.h \
		BlockFactory.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TetrisScene.o TetrisScene.cpp

QTetrisWindow.o: QTetrisWindow.cpp QTetrisWindow.h \
		TetrisScene.h \
		TetrisGrid.h \
		Block.h \
		GameBorder.h \
		BlockFactory.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QTetrisWindow.o QTetrisWindow.cpp

Block.o: Block.cpp Block.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Block.o Block.cpp

BlockFactory.o: BlockFactory.cpp BlockFactory.h \
		Block.h \
		LineBlock.h \
		LBlock.h \
		JBlock.h \
		TBlock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BlockFactory.o BlockFactory.cpp

LineBlock.o: LineBlock.cpp LineBlock.h \
		Block.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LineBlock.o LineBlock.cpp

LBlock.o: LBlock.cpp LBlock.h \
		Block.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LBlock.o LBlock.cpp

JBlock.o: JBlock.cpp JBlock.h \
		Block.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o JBlock.o JBlock.cpp

TBlock.o: TBlock.cpp TBlock.h \
		Block.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TBlock.o TBlock.cpp

GameBorder.o: GameBorder.cpp GameBorder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GameBorder.o GameBorder.cpp

main.o: main.cpp QTetrisWindow.h \
		TetrisScene.h \
		TetrisGrid.h \
		Block.h \
		GameBorder.h \
		BlockFactory.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

moc_TetrisGrid.o: moc_TetrisGrid.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TetrisGrid.o moc_TetrisGrid.cpp

moc_QTetrisWindow.o: moc_QTetrisWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QTetrisWindow.o moc_QTetrisWindow.cpp

moc_BlockFactory.o: moc_BlockFactory.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_BlockFactory.o moc_BlockFactory.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

