######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 9 20:06:02 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS = TetrisGrid.h \
          QTetrisWindow.h \
          Block.h 
SOURCES = TetrisGrid.cpp \
          QTetrisWindow.cpp \
          Block.cpp \ 
          main.cpp
